//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject003.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mobile_No { get; set; }
        public string Email_ID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    }
}
